### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by zyhhh123** [liumency/SYSU-CD#1]
Hi!
    I am zhao yang.And my current research oriention is deep learning for change detetcion.But I have not datasets.Please tell me where are your datasets.If your dataset is not release,please provide other dataset  mentioned in your paper(such as OSCD) for me. Thank you!

**Comment by liumency** [comment]
> Hi! I am zhao yang.And my current research oriention is deep learning for change detetcion.But I have not datasets.Please tell me where are your datasets.If your dataset is not release,please provide other dataset mentioned in your paper(such as OSCD) for me. Thank you!

You can download the SYSU-CD from https://pan.baidu.com/share/init?surl=5lQPG_hXZbLp91VywwcT7Q （code: mlls）.
